# Generated by Django 5.1.4 on 2025-01-12 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='idx_answers_question_id',
        ),
        migrations.RemoveIndex(
            model_name='status',
            name='idx_status_user_id',
        ),
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='status',
            table=None,
        ),
    ]
