# Generated by Django 5.1.4 on 2025-01-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_idx_answers_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='match_in_round_index',
        ),
        migrations.AddField(
            model_name='status',
            name='matches_per_round',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='status',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='answer_difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='question_difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
